development:
  adapter: postgresql
  encoding: unicode
  database: inclass_awesomeanswers_development
  pool: 5
  username: tammam
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: inclass_awesomeanswers_test
  pool: 5
  username: tammam
  password: 